<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv('/datasets/insurance.csv')
display(data.head())
data.info()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

- $B$ — случайная квадратная обратимая матрица

Предсказания:

$$
a_1 = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

**Ответ:** Не измениться

**Обоснование:** Если качество не измениться, то не изменяться и предсказания, следовательно, 
$$
a_1 = a_2
$$
$$
X_1 w_1 = X_2 w_2
$$

где
$$
X_2 = X_1 B
$$
$$
w_2 = (X_2^T X_2)^{-1} X_2^T y
$$
Получается, что
$$
X_1 (X_1^T X_1)^{-1} X_1^T y = X_2 (X_2^T X_2)^{-1} X_2^T y
$$
$$
X_1 (X_1^T X_1)^{-1} X_1^T y = X_1 B ((X_1 B)^T (X_1 B))^{-1} (X_1 B)^T y
$$
Сокращаем 
$$
X_1 y
$$
Следовательно
$$
(X_1^T X_1)^{-1} X_1^T = B ((X_1)^T)^{-1} ((B)^T)^{-1} X_1^{-1} B^{-1} X_1^T B^T
$$
Сокращаем 
$$
X_1^T
$$
Получаем 1 в 
$$
B^T ((B)^T)^{-1}
$$
$$
B^{-1} B
$$
После сокращений получаем, что
$$
X_1^T X_1)^{-1} = ((X_1)^T)^{-1} X_1^{-1}
$$
$$
1 = 1
$$
Что и требовалось доказать

## Алгоритм преобразования

**Алгоритм**

1. Создадим случайную квадратную матрицу размера n x n, где n - количесвто признаков обучающей матрицы.
2. Проверим, обратима ли эта квадратная матрица.
3. Если матрица из п.1 обратима, то перемножем матрицу признаков(m x n) на матрицу из п.1(n x n)
4. Как итог получим защифрованную матрицу признаков размера m x n

**Обоснование**

Из доказательства выше следует, что домнажение матрицы на обратимую не повлияет на результаты обучения и метрики качества. Взяв личные данные пользователя  и домножив их на обратимую матрицу мы их зашифровали и тем самым защитили клиентов страховой компании.

## Проверка алгоритма

In [3]:
# Получение обратимой квадратной матрицы
data_norm = np.random.normal(size = [4, 4])
try:
    np.linalg.inv(data_norm)
    print('data_norm - обратимая')
except:
    print('data_norm не обратимая')
print(data_norm)

data_norm - обратимая
[[-1.13828475 -2.02288893 -1.78066888  1.79731154]
 [-0.54739343 -1.41948947  0.62725513  2.51856612]
 [-1.69597179 -1.15247159  0.27895772 -1.33057192]
 [ 0.4002641  -1.56930633 -0.34327821 -0.65765397]]


In [4]:
# Получение целевого и остальных признаков для обучения моделей
features = data.drop('Страховые выплаты', axis = 1)
features_mat = features @ data_norm
target = data['Страховые выплаты']

In [5]:
# обучение модели с не преобразованными данными
model_1 = LinearRegression()
model_1.fit(features, target)
predictions = model_1.predict(features)
print('R2_score - ',r2_score(target, predictions))

R2_score -  0.42494550286668


In [6]:
# обучение модели с преобразованными данными
model_2 = LinearRegression()
model_2.fit(features_mat, target)
predictions = model_2.predict(features_mat)
print('R2_score - ',r2_score(target, predictions))

R2_score -  0.42494550286668664


Из метрик r2 видим, что качество модели не изменилось

## Вывод

В ходе данного проекта были изучены данные клиентов страховой компании. Было доказано, что если матрицу признаков домножить на обратимую, то качество модели, обучаемой на этих данные не поменятся, но при этом истинные данные клиентов будут зашифрованы.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [x]  Указан правильный вариант ответа
    - [x]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования